### ISSUE TITLE
[Build] Create build target to produce embeddable client & hud files

### ISSUE THREAD

**Issue by mike-kaufman** [Glimpse/Glimpse.Client.Prototype#43] opened 2016-03-16 15:57 UTC
Need to "script" the following:

1. Set FAKE_SERVER & DIAGNOSTICS to false in wepback.config.js
	
2. Build client
	Cd d:\glimpse\Glimpse.client.Prototype
	Gulp build-prod
	Copy dist\main.js dist\main.min.js
	Gulp build-dev
	

3. Build HUD	
	Cd d:\glimpse\Glimpse.client.Prototype\_temp\hud
	Npm install
	Gulp build-prod
	Copy dist\main.js dist\hud.min.js
	Gulp build-dev
	Rename dist\main.js hud.js
	
4.  "consume" task should be written in consuming projects to pull these into appropriate locations.

**Comment by avanderhoorn** [comment] 2016-03-16 15:58
Most likely this will be wrapped up in a `gulp export` task.

**Comment by philliphoff** [comment] 2016-04-11 16:10
Closing as duplicate of #56.

**Closed by philliphoff** 2016-04-11 16:10 UTC
